import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import saveData from '@/elasticsearch/savedata'
import getData from '@/elasticsearch/getdata'
import Data from '@/components/Data'


const inter = Inter({ subsets: ['latin'] })

type Props = {
  data: any
}

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="dataCheck">

          <Data data={data}/>
        
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {

  await saveData()
  const data = await getData('Have you been diagnosed with a mental health condition by a medical professional?')
  console.log(data)

  return {
    props: {
      data: data,
    }
  }
}

/*  {data.map((x: any) => (
        <Data data={x} key={x.id} />
      ))}  */
